<style>
    body{
    background:#212124;
    display:grid;
    place-content:center;
    padding:50px 0 0 0;
    color:white;
}
#retour{
    width:70px;
    height:70px;
    position:fixed;
    bottom:2cm;
    left:0.54cm;
    border-radius:50px;
}
    img{
    max-width:250px;
}
#PDP{
    width:50px;
    border-radius:50px;
}
.th{
    width:300px;
    padding:10px;
    background:#3f3f3f;
    border-radius:60px;
    display:flex;
    align-items:center;
}
.th h5{
    margin-left:10px;
}
.td{
    display:grid;
    place-content:center;
}
</style>